# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/Protocentral/zephyr-healthypi5
    - name: protocentral
      url-base: https://github.com/Protocentral

  projects:
    - name: zephyr-healthypi5
      remote: protocentral
      revision: v3.7-branch
      import: 
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis-dsp
          - cmsis      # required by the ARM port
          - hal_rpi_pico # required by the RPi Pico port
          - littlefs
          - lvgl      
          - mcuboot
          - zcbor  
          - tinycrypt
          - fatfs
          - libmetal
          - mbedtls
          - liblc3
          - net-tools
          - picolibc
          - hal_espressif
          
#    - name: max30001
#      repo-path: protocentral_max30001_zephyr_driver
#      remote: protocentral
#      revision: main
#      path: drivers/sensor/max30001