name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.12
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: healthypi5_zephyr

      - name: Initialize
        working-directory: healthypi5_zephyr
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build Basic firmware
        working-directory: healthypi5_zephyr
        run: |
          rm -rf *.uf2
          west build -p always -b healthypi5_rp2040 app -DEXTRA_CONF_FILE='overlay-bt.conf;overlay-logger-sd.conf' -DEXTRA_DTC_OVERLAY_FILE=healthypi5_rp2040_sd.overlay 
          mv build/zephyr/zephyr.uf2 healthypi5_basic.uf2

      - name: Build display firmware for ST7796
        working-directory: healthypi5_zephyr
        run: |
          west build -t pristine
          west build -p auto -b healthypi5_rp2040 app  -DEXTRA_CONF_FILE='overlay-bt.conf;overlay-display-st7796.conf;overlay-logger-sd.conf' -DEXTRA_DTC_OVERLAY_FILE='healthypi5_rp2040_display_st7796.overlay;healthypi5_rp2040_sd.overlay'
          mv build/zephyr/zephyr.uf2 healthypi5_display_st7796.uf2

      - name: Build display firmware for ILI9488
        working-directory: healthypi5_zephyr
        run: |
          west build -t pristine
          west build -p auto -b healthypi5_rp2040 app  -DEXTRA_CONF_FILE='overlay-bt.conf;overlay-display-ili9488.conf;overlay-logger-sd.conf' -DEXTRA_DTC_OVERLAY_FILE='healthypi5_rp2040_display_ili9488.overlay;healthypi5_rp2040_sd.overlay'
          mv build/zephyr/zephyr.uf2 healthypi5_display_ili9488.uf2

      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "healthypi5_zephyr/*.uf2"
          token: ${{ secrets.GITHUB_TOKEN }}