name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: healthypi5_zephyr

      - name: Initialize
        working-directory: healthypi5_zephyr
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build base firmware
        working-directory: healthypi5_zephyr
        run: |
          rm -rf *.uf2
          west build -p auto -b healthypi5_rp2040 app
          mv build/zephyr/zephyr.uf2 healthypi5_base.uf2

      - name: Build display firmware
        working-directory: healthypi5_zephyr
        run: |
          west build -t pristine
          west build -p auto -b healthypi5_rp2040 app -DEXTRA_CONF_FILE=overlay-display.conf
          mv build/zephyr/zephyr.uf2 healthypi5_display.uf2

      - name: Build BLE firmware
        working-directory: healthypi5_zephyr
        run: |
          west build -t pristine
          west build -p auto -b healthypi5_rp2040 app -DEXTRA_CONF_FILE=overlay-bt.conf
          mv build/zephyr/zephyr.uf2 healthypi5_ble.uf2
      
      - name: Build BLE firmware with MCUBoot
        working-directory: healthypi5_zephyr
        run: |
          west build -t pristine
          west build -p auto -b healthypi5_rp2040 app --sysbuild "-DEXTRA_CONF_FILE=overlay-boot.conf;overlay-bt.conf" "-DEXTRA_DTC_OVERLAY_FILE=healthypi5_rp2040_mcuboot.overlay"
          hexmerge.py -o build/merged_boot.hex --no-start-addr build/mcuboot/zephyr/zephyr.hex build/app/zephyr/zephyr.signed.hex
          hex2bin.py build/merged_boot.hex build/merged_boot.bin
          ../zephyr/scripts/build/uf2conv.py build/merged_boot.bin --convert -f 0xe48bff56 -b 0x10000000 -o build/merged_boot.uf2
          mv build/merged_boot.uf2 healthypi5_ble_boot.uf2
      
      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "healthypi5_zephyr/*.uf2"
          token: ${{ secrets.GITHUB_TOKEN }}