name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Free Disk Space
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          sudo docker system prune -af
          echo "After cleanup:"
          df -h
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: healthypi5_zephyr

      - name: Initialize and Build
        run: |
          docker run --rm \
            -v $(pwd)/healthypi5_zephyr:/workspace \
            -w /workspace \
            -e CMAKE_PREFIX_PATH=/opt/toolchains \
            ghcr.io/zephyrproject-rtos/ci:latest \
            bash -c "
              set -e
              west init -l .
              west update -o=--depth=1 -n
              
              # Build ILI9488 variant
              west build -p auto -b healthypi5 app \
                -DEXTRA_CONF_FILE='overlay-display-ili9488.conf;overlay-logger-sd.conf' \
                -DEXTRA_DTC_OVERLAY_FILE='healthypi5_rp2040_display_ili9488.overlay'
              mv build/zephyr/zephyr.uf2 healthypi5_ili9488.uf2
              
              # Build ST7796 variant
              west build -p always -b healthypi5 app \
                -DEXTRA_CONF_FILE='overlay-display-st7796.conf;overlay-logger-sd.conf' \
                -DEXTRA_DTC_OVERLAY_FILE='healthypi5_rp2040_display_st7796.overlay'
              mv build/zephyr/zephyr.uf2 healthypi5_st7796.uf2
            "
      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "healthypi5_zephyr/*.uf2"
          token: ${{ secrets.GITHUB_TOKEN }}